site: Harsh Browns
url: https://visitmy.website
title: Harsh Browns
description: Steve Messer’s website.
default_img: /assets/images/8a595a78177bf62b.jpeg
author:
  twitter: stevenjmesser
  name: Steve Messer
  avatar:
  email: #youremail
  url: https://visitmy.website
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  - .ai_related_posts_cache.sqlite3
  - .ai_related_posts_cache.sqlite3-journal
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-webmention_io
  - jekyll_ai_related_posts

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
webmentions:
  username: visitmy.website
  throttle_lookups:
    last_week: weekly
    last_month: monthly
    last_year: monthly
    older: every 3 months

ai_related_posts:
  openai_api_key: 

markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"